/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as No_authRouteImport } from './routes/_no_auth'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as No_authSignupRouteImport } from './routes/_no_auth/signup'
import { Route as No_authSigninRouteImport } from './routes/_no_auth/signin'

const No_authRoute = No_authRouteImport.update({
  id: '/_no_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const No_authSignupRoute = No_authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => No_authRoute,
} as any)
const No_authSigninRoute = No_authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => No_authRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/signin': typeof No_authSigninRoute
  '/signup': typeof No_authSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/signin': typeof No_authSigninRoute
  '/signup': typeof No_authSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_no_auth': typeof No_authRouteWithChildren
  '/_no_auth/signin': typeof No_authSigninRoute
  '/_no_auth/signup': typeof No_authSignupRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/signin' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/signin' | '/signup'
  id:
    | '__root__'
    | '/_auth'
    | '/_no_auth'
    | '/_no_auth/signin'
    | '/_no_auth/signup'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  No_authRoute: typeof No_authRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_no_auth': {
      id: '/_no_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof No_authRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_no_auth/signup': {
      id: '/_no_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof No_authSignupRouteImport
      parentRoute: typeof No_authRoute
    }
    '/_no_auth/signin': {
      id: '/_no_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof No_authSigninRouteImport
      parentRoute: typeof No_authRoute
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface No_authRouteChildren {
  No_authSigninRoute: typeof No_authSigninRoute
  No_authSignupRoute: typeof No_authSignupRoute
}

const No_authRouteChildren: No_authRouteChildren = {
  No_authSigninRoute: No_authSigninRoute,
  No_authSignupRoute: No_authSignupRoute,
}

const No_authRouteWithChildren =
  No_authRoute._addFileChildren(No_authRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  No_authRoute: No_authRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
