services:
  db:
    env_file: ./docker/.env
    image: docker.io/postgres:18.2
    container_name: theapp_db
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ./docker/volumes/db:/var/lib/postgresql:Z,U
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  garage:
    image: docker.io/dxflrs/garage:v2.2.0
    container_name: theapp_garage
    restart: unless-stopped
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - ./docker/garage.toml:/etc/garage.toml:ro,Z
      - ./docker/volumes/garage_meta:/tmp/meta:Z,U
      - ./docker/volumes/garage_data:/tmp/data:Z,U
    environment:
      RUST_LOG: info

  valkey:
    image: docker.io/valkey/valkey
    container_name: theapp_valkey
    restart: unless-stopped
    ports:
      - 6379:6379

  # Production services

  server:
    profiles:
      - prod
    env_file: ./docker/.env
    build:
      dockerfile: ./apps/server/Dockerfile
    container_name: theapp_server
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      garage:
        condition: service_started
      db:
        condition: service_healthy

  webapp:
    profiles:
      - prod
    build:
      dockerfile: ./apps/webapp/Dockerfile
    container_name: theapp_webapp
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - server

  caddy:
    profiles:
      - prod
    env_file: ./docker/.env
    image: docker.io/caddy:latest
    container_name: theapp_caddy
    restart: unless-stopped
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./docker/volumes/caddy_data:/data:Z,U
      - ./docker/volumes/caddy_config:/config:Z,U
    depends_on:
      - webapp

  # Development services

  garage_ui:
    profiles:
      - dev
    image: docker.io/khairul169/garage-webui:latest
    container_name: theapp_garage-ui
    restart: unless-stopped
    volumes:
      - ./docker/garage.toml:/etc/garage.toml:ro,Z
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: http://garage:3903
      S3_ENDPOINT_URL: http://garage:3900
    depends_on:
      - garage
